from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """Structured research plan generated by the planner agent."""

    intent: str
    core_topics: list[str]
    related_topics: list[str] = Field(default_factory=list)
    search_terms: list[str]
    allowed_domains: list[str] = Field(default_factory=list)
    freshness: Literal["pd", "pw", "pm", "py", "custom"] = "pw"
    quality_constraints: list[str] = Field(default_factory=list)


class SearchResult(BaseModel):
    """A normalized search result returned by the web search tool."""

    title: str | None = None
    url: str
    snippet: str = ""
    source_domain: str | None = None
    engine: str | None = None
    category: str | None = None
    query: str | None = None
    retrieved_at: str | None = None


class SearchResponse(BaseModel):
    results: list[SearchResult]
    query: str | None = None


class CrawlDocument(BaseModel):
    """A crawled page normalized into a retrievable document."""

    url: str
    title: str | None = None
    text: str
    allowed: bool = True
    source_domain: str | None = None
    error: str | None = None


class ReportArtifact(BaseModel):
    title: str
    markdown: str
    citations: list[str] = Field(default_factory=list)
    source_urls: list[str] = Field(default_factory=list)
